version: '3.4'

services:
  ocelot.service_1:
    image: ${DOCKER_REGISTRY-}ocelotservice
    build:
      context: .
      dockerfile: Ocelot.Service/Dockerfile
    networks:
      - test_ocelot
  ocelot.service_2:
    image: ${DOCKER_REGISTRY-}ocelotservice
    build:
      context: .
      dockerfile: Ocelot.Service/Dockerfile
    networks:
      - test_ocelot
  ocelot.service_3:
    image: ${DOCKER_REGISTRY-}ocelotservice
    build:
      context: .
      dockerfile: Ocelot.Service/Dockerfile
    networks:
      - test_ocelot
  ocelot.gateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: Ocelot.Gateway/Dockerfile
    networks:
      - test_ocelot

  grpc.web.server:
    image: ${DOCKER_REGISTRY-}grpcwebserver
    build:
      context: .
      dockerfile: Grpc.Web.Server/Dockerfile
    networks:
      - test_ocelot

  grpc.web.client:
    image: ${DOCKER_REGISTRY-}grpcwebclient
    build:
      context: .
      dockerfile: Grpc.Web.Client/Dockerfile
    networks:
      - test_ocelot

  grpc.cli.client:
    image: ${DOCKER_REGISTRY-}grpccliclient
    build:
      context: .
      dockerfile: Grpc.Cli.Client/Dockerfile
    depends_on: 
      - grpc.web.server

networks:
  test_ocelot:



